### ISSUE TITLE
Stack alignment

### ISSUE THREAD

**Issue by Amanieu** [nathan7/libfringe#40]
Some platforms have requirements regarding stack alignment on function entry (16 bytes for x86, x86_64 and aarch64, 8 bytes for arm). Should it be the `Stack`'s responsibility to ensure alignment or should the context initialization perform a suitable alignment (by aligning the address returned by `Stack::base`)?

**Comment by Amanieu** [comment]
As a side note, we should probably be using the `"alignstack"` inline asm modifier on all platforms since it is specifically designed for asm that performs function calls.

**Comment by whitequark** [comment]
> Should it be the Stack's responsibility to ensure alignment or should the context initialization perform a suitable alignment (by aligning the address returned by Stack::base)?

Stack's. The less complexity in per-platform code, the better; and 16 bytes is at the moment the highest common alignment. This should be documented as Stack's contract.

**Comment by whitequark** [comment]
> As a side note, we should probably be using the "alignstack" inline asm modifier on all platforms since it is specifically designed for asm that performs function calls.

Using it where exactly and why? 
  * We definitely shouldn't be using it in the swap itself, because that forces creation of a frame pointer.
  * There's no point in using it in the swap trampoline.
  * Even if you use it in the init trampoline, you still have to calculate CFI offsets towards the top of the stack, so it brings you no benefit.
